name: Browser Tests

on:
  workflow_dispatch:
  push:

jobs:
  see_if_should_skip:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@36feb0d8d062137530c2e00bd278d138fe191289
        with:
          cancel_others: 'false'
          github_token: ${{ github.token }}
          paths: '[".github/workflows/browser-test.yml","assets/**","content/**","data/**","includes/**","javascripts/**","jest-puppeteer.config.js","jest.config.js","layouts/**","lib/**","middleware/**","package-lock.json","package.json","server.js","translations/**","webpack.config.js"]'

  build:
    needs: see_if_should_skip
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.see_if_should_skip.outputs.should_skip != 'true' }}
        name: Checkout
        uses: actions/checkout@v4

      - if: ${{ needs.see_if_should_skip.outputs.should_skip != 'true' }}
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - if: ${{ needs.see_if_should_skip.outputs.should_skip != 'true' }}
        name: Install dependencies
        run: npm install

      - if: ${{ needs.see_if_should_skip.outputs.should_skip != 'true' }}
        name: Run browser tests
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: npm run browser-test
